
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/comments_db
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB=comments_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  celery:
    build: ./backend
    command: celery -A comments_app worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/comments_db
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB=comments_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: